[project]
name = "custom-mcp-server"
version = "0.1.0"
description = "Arindam's Custom MCP Server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
]
